language: go

go:
    - 1.7
    - 1.8
    - tip

go_import_path: github.com/intel/tfortools

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get github.com/mattn/goveralls

script:
   - go env
   - $GOPATH/bin/goveralls -v -service=travis-ci --package github.com/intel/tfortools
   - gometalinter --tests --vendor --disable-all --enable=misspell --enable=vet --enable=ineffassign --enable=gofmt --enable=gocyclo --cyclo-over=15 --enable=golint --enable=errcheck --enable=deadcode ./...
